# Generated by Django 5.1.3 on 2025-01-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipoligono', '0002_resultadotiro_numero_carril'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioArma',
        ),
    ]
