# Generated by Django 5.1.3 on 2025-01-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipoligono', '0005_codigorecuperacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fracciontiro',
            name='unique_leccion_tiradores',
        ),
    ]
