# Generated by Django 5.1.3 on 2025-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apipoligono', '0006_remove_fracciontiro_unique_leccion_tiradores'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fracciontiro',
            constraint=models.UniqueConstraint(fields=('id_leccion', 'tiradores_totales'), name='unique_leccion_tiradores'),
        ),
    ]
