# Generated by Django 5.1.3 on 2025-01-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apipoligono', '0007_fracciontiro_unique_leccion_tiradores'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fracciontiro',
            name='unique_leccion_tiradores',
        ),
    ]
